# use new container-based infrastructure
sudo: false

language: python
install: pip install tox
script: tox

# install codecov and publish coverage only after a successful build
after_success:
  - pip install codecov
  - codecov

