# use new container-based infrastructure
sudo: false

language: python

addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - python3.5

install: pip install tox
script: tox

# install codecov and publish coverage only after a successful build
after_success:
  - pip install codecov
  - codecov

