# use new container-based infrastructure
sudo: false

language: python
install: pip install tox
script: tox

# install coveralls and publish coverage only after a successful build
after_success:
  - pip install coveralls
  - coveralls # coveralls submit coverage report

